const { chromium } = require('C:/Users/a/node_modules/playwright-core');
const fs = require('node:fs');
const path = require('node:path');
const out = path.resolve('docs/qa/2026-10-03');
fs.mkdirSync(out, { recursive: true });

(async () => {
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
  const page = await context.newPage();
  const results = { errors: [], requestsFailed: [], checks: {} };
  page.on('pageerror', error => results.errors.push(error.message));
  page.on('requestfailed', request => results.requestsFailed.push({url:request.url(),error:request.failure()}));
  const shot = async name => { await page.screenshot({ path: path.join(out, name + '.png'), fullPage: true }); };
  const read = async () => page.evaluate(() => ({ text: document.body.innerText, saved: JSON.parse(localStorage.getItem('claude_game_save_v1')), viewport: { width: innerWidth, height: innerHeight }, canvas: document.querySelector('canvas')?.getBoundingClientRect().toJSON(), panel: document.querySelector('#bottom-panel')?.getBoundingClientRect().toJSON(), documentHeight: document.documentElement.scrollHeight }));
  await page.goto('https://www.fungood.co.kr/claude_game/', { waitUntil: 'networkidle' });
  await page.locator('canvas').waitFor();
  await shot('01-idle-mobile');
  results.checks.initial = await read();
  await page.waitForTimeout(18000);
  await page.getByRole('button', {name:'스킬', exact:true}).click();
  await page.waitForTimeout(150);
  results.checks.skillsBefore = await read();
  await page.locator('[data-skill-id="power_strike"]').click();
  await page.waitForTimeout(150);
  results.checks.skillsAfter = await read();
  await shot('02-skills-mobile');
  await page.getByRole('button', {name:'설정', exact:true}).click();
  await page.waitForTimeout(150);
  await page.getByRole('button', {name:'등급 변경'}).click();
  await page.waitForTimeout(150);
  results.checks.settings = await read();
  await shot('03-settings-mobile');
  await page.getByRole('button', {name:'상점', exact:true}).click();
  await page.waitForTimeout(150);
  results.checks.shopBefore = await read();
  await page.getByRole('button', {name:'뽑기 (20골드)'}).click();
  await page.waitForTimeout(150);
  results.checks.shopAfter = await read();
  await shot('04-shop-mobile');
  await page.getByRole('button', {name:'장비', exact:true}).click();
  await page.waitForTimeout(150);
  const restore = page.locator('[data-action="restore-scrapbook-item"]');
  results.checks.equipmentBefore = await read();
  if (await restore.count()) {
    await restore.first().click();
    await page.waitForTimeout(150);
    results.checks.equipmentAfter = await read();
  }
  await shot('05-equipment-mobile');
  const handle = await page.locator('.panel-handle').boundingBox();
  await page.mouse.move(handle.x + 20, handle.y + 2);
  await page.mouse.down();
  await page.mouse.move(handle.x + 20, handle.y + 42, {steps:8});
  await page.mouse.up();
  results.checks.panelDrag = { minimized: await page.locator('#bottom-panel').evaluate(el => el.classList.contains('minimized')) };
  await page.evaluate(() => scrollTo(0, 0));
  await page.locator('canvas').click({ position: {x:180,y:100} });
  await page.waitForTimeout(2000);
  results.checks.combat = await read();
  await shot('06-combat-mobile');
  const canvas = await page.locator('canvas').boundingBox();
  await page.mouse.move(canvas.x+180, canvas.y+320);
  await page.mouse.down();
  await page.mouse.move(canvas.x+70, canvas.y+140,{steps:10});
  await page.mouse.up();
  await shot('07-combat-moved-mobile');
  await page.waitForFunction(() => getComputedStyle(document.querySelector('#bottom-panel')).display !== 'none', {timeout:45000});
  results.checks.combatEnded = await read();
  await shot('08-combat-ended-mobile');
  await page.reload({waitUntil:'networkidle'});
  await page.getByRole('button', {name:'스킬',exact:true}).click();
  await page.waitForTimeout(150);
  results.checks.reload = await read();
  await page.setViewportSize({width:360,height:640});
  await page.evaluate(() => scrollTo(0,0));
  results.checks.smallMobile = await read();
  await shot('09-small-mobile');
  await page.setViewportSize({width:1440,height:900});
  await page.evaluate(() => scrollTo(0,0));
  await shot('10-desktop');
  results.checks.desktop = await read();
  await page.goto('https://www.fungood.co.kr/game_portal/',{waitUntil:'networkidle'});
  const card = page.locator('.game-card').filter({has:page.getByRole('heading',{name:'Claude Game',exact:true})}).first();
  await card.scrollIntoViewIfNeeded();
  await card.screenshot({path:path.join(out,'11-portal-card.png')});
  await card.getByRole('link',{name:'▶ 플레이',exact:true}).click();
  await page.locator('iframe').waitFor();
  results.checks.portal = {url:page.url(),iframe:await page.locator('iframe').getAttribute('src')};
  await page.frameLocator('iframe').locator('canvas').waitFor();
  await shot('12-portal-play');
  fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));
  console.log(JSON.stringify(results,null,2));
  await browser.close();
})().catch(error => {console.error(error);process.exit(1)});
